#!/usr/bin/python3

import re
import click

from commands.pull_command import run_pull
from commands.run_command import run_run

@click.group()
def cli():
    pass

@click.command()
@click.argument('image_name')
def pull(image_name):
    match = re.match(r'(?P<image>[^/:]+)(:)?(?P<tag>[^/:]*)', image_name)
    if not match:
        print('invalid args')
        sys.exit(1)
    image = match.group('image')
    tag = match.group('tag') if match.group('tag') else 'latest'
    run_pull(image, tag)

@click.command()
@click.argument('image_name')
@click.argument('command')
def run(image_name, command):
    click.echo(f'Running {image_name} container: {command}')
    run_run()

cli.add_command(pull)
cli.add_command(run)

if __name__ == '__main__':
    cli()